apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-gcs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-gcs-test-sc
  csi:
    driver: storage.csi.cloud.google.com
    volumeHandle: csi-gcs
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: default
